In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('/content/Market_Basket_Optimisation.csv', header=None)
dataset.head()

0          1           2                 3             4   \
0         shrimp    almonds     avocado    vegetables mix  green grapes   
1        burgers  meatballs        eggs               NaN           NaN   
2        chutney        NaN         NaN               NaN           NaN   
3         turkey    avocado         NaN               NaN           NaN   
4  mineral water       milk  energy bar  whole wheat rice     green tea   

                 5     6               7             8             9   \
0  whole weat flour  yams  cottage cheese  energy drink  tomato juice   
1               NaN   NaN             NaN           NaN           NaN   
2               NaN   NaN             NaN           NaN           NaN   
3               NaN   NaN             NaN           NaN           NaN   
4               NaN   NaN             NaN           NaN           NaN   

               10         11     12     13             14      15  \
0  low fat yogurt  green tea  honey  salad  mineral water  salmon   
1             NaN        NaN    NaN    NaN            NaN     NaN   
2             NaN        NaN    NaN    NaN            NaN     NaN   
3             NaN        NaN    NaN    NaN            NaN     NaN   
4             NaN        NaN    NaN    NaN            NaN     NaN   

                  16               17       18         19  
0  antioxydant juice  frozen smoothie  spinach  olive oil  
1                NaN              NaN      NaN        NaN  
2                NaN              NaN      NaN        NaN  
3                NaN              NaN      NaN        NaN  
4                NaN              NaN      NaN        NaN

In [3]:
dataset.shape

(7501, 20)

In [4]:
#this dataset represented the transaction in 1 week. 
#the index correspond with 7501 transactions respectively
#each transaction consist uncertainly number of product, but we know the max number is 20

In [5]:
! pip install apyori
#here we going to install the module apyori
#this module will help us in association rule case

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [6]:
transactions = []
for i in range(0,7501):
  transactions.append([str(dataset.values[i,j]) for j in range(0,20)])

#the apriori function, only work with list data instead of table data. hence we move the values from dataset table to transactions list

In [7]:
from apyori import apriori 
rules = apriori(transactions=transactions, min_support=0.003, min_confidence=0.3, min_lift=3, min_length=2, max_length=2)
#here we create an instance, consist apriori function.

In [8]:
list_rules = list(rules)
list_rules

[RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'ground beef', 'herb & pepper'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'ground beef', 'tomato sauce'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'groun

In [10]:
#from output above, we need to recognize each element inside list_rules:
#index 0 = RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}),
  #index [0][0] = 'mushroom cream sauce'
  #index [0][1] = 'escalope'
#index 1 = support=0.005732568990801226
#index 2 = ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]
  #index [2][0][0] = 'mushroom cream sauce'
  #index [2][0][1] = 'escalope'
  #index [2][0][2] = 'confidence=0.3006993006993007'
  #index [2][0][3] = lift=3.790832696715049'

In [16]:
#create function to visualize the rules in table form. so we know the best recomendation for costumers based on support, confidence and lift
def check_rules(outcome):
  left_side   = [tuple(result[2][0][0])[0]for result in outcome]
  right_side  = [tuple(result[2][0][1])[0]for result in outcome]
  support     = [result[1]for result in outcome]
  confidence  = [result[2][0][2] for result in outcome]
  lift        = [result[2][0][3] for result in outcome]
  return list(zip(left_side, right_side, support, confidence, lift))

In [19]:
rules_table = pd.DataFrame(check_rules(list_rules), columns=['lieft_side', 'right_side', 'support', 'confidence', 'lift'])
rules_table.nlargest(n=10, columns='lift')

lieft_side   right_side   support  confidence      lift
1                 pasta     escalope  0.005866    0.372881  4.700812
4                 pasta       shrimp  0.005066    0.322034  4.506672
3          tomato sauce  ground beef  0.005333    0.377358  3.840659
0  mushroom cream sauce     escalope  0.005733    0.300699  3.790833
2         herb & pepper  ground beef  0.015998    0.323450  3.291994

In [ ]:
#from rules_table above, we know that, in the second transaction, the costumers who bought pasta, are likely going to bought escalope. with the the support 0.005866, confidence=0.372881, and lift=4.700812
#similarly with the fourth, third, and further transactions
#from this table we can recomended to decision maker, to create a kupon, addressed for costumers who bought pasta, to get escalope or shrimp for free, in order to increasing the sales 


# **interpretation:**


1.   **from rules_table above, we know that, in the second transaction, the costumers who bought pasta, are likely going to bought escalope. with the the support 0.005866, confidence=0.372881, and lift=4.700812**
2.   **similarly with the fourth, third, and further transactions**
3.   **from this table we can recomended to decision maker, to create a kupon, addressed for costumers who bought pasta, to get escalope or shrimp for free, in order to increasing the sales**

